months:
  - 2025-01
months_from_outputs: false
no_site: false
triage_force: false
summary_force: false
include_borderline: false
triage_sleep_seconds: 0.0
summary_sleep_seconds: 0.0
stop_on_rate_limit: true
sync_cache_from_outputs: true
max_candidates: null
max_accepted: null
env_path: null
